In [3]:
import numpy as np

#Conversion of List into Array.

In [4]:
list1 = np.array([1, 2, 3, 4, 5])

In [5]:
list1

array([1, 2, 3, 4, 5])

#Conversion of Tuple into Array.

In [6]:
tuple1 = np.array(('a', 'b', 'c', 'd', 'f'))

In [7]:
tuple1

array(['a', 'b', 'c', 'd', 'f'], dtype='<U1')

*Generate an array with zero number array.*

In [8]:
zero = np.zeros([6])

In [15]:
zero

array([0., 0., 0., 0., 0., 0.])

*Generate an array with one number array.*

In [10]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

*Generate an array with random number array.*

In [11]:
np.empty([5, 6, 1])

array([[[8.63422934e-312],
        [8.63399198e-312],
        [0.00000000e+000],
        [0.00000000e+000],
        [1.21572612e-224],
        [1.16097020e-028]],

       [[6.37112413e-067],
        [2.73418116e-052],
        [3.53851881e-057],
        [5.01163173e+217],
        [8.37170074e-144],
        [4.04754621e-037]],

       [[1.74248061e-076],
        [5.33862893e-091],
        [2.21658012e-056],
        [5.01163113e+217],
        [5.49419094e-143],
        [9.80058441e+252]],

       [[7.50189709e+247],
        [1.35617292e+248],
        [3.25616199e-032],
        [2.81185478e-033],
        [9.58262694e+169],
        [2.00220142e-052]],

       [[5.99040447e+174],
        [5.04621361e+180],
        [8.37170571e-144],
        [9.30350598e+199],
        [5.60230216e-067],
        [8.75811408e-308]]])

#Conversion of list variable in array

In [12]:
l = [1,2,3,4]
np.array(l)

array([1, 2, 3, 4])

*Conversion of tuple variable into array.*

In [13]:
t = ('a', 'b', 'c')
np.array(t)

array(['a', 'b', 'c'], dtype='<U1')

*Range in Numpy*

In [14]:
np.arange(100, 500, 5)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220, 225,
       230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290,
       295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345, 350, 355,
       360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415, 420,
       425, 430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485,
       490, 495])

*To find the shap of an array.*

In [28]:
l = np.array([1,3,5,6])
sh_var = np.array([23, 436, 24, 4, 6])

print(l.shape, sh_var.shape)

(4,) (5,)


In [30]:
sh_var = np.empty([20, 43, 1])
sh_var.shape

(20, 43, 1)

*Reshape the array.*

In [31]:
sh_var.reshape((430, 2))

array([[ 8.63433091e-312,  8.63441277e-312],
       [ 0.00000000e+000,  8.63434410e-312],
       [ 4.94065646e-324,  8.63434410e-312],
       [ 4.94065646e-324,  8.63434410e-312],
       [ 1.18575755e-322,  8.63461046e-312],
       [             nan,  8.63461046e-312],
       [ 4.94065646e-324,  1.27319747e-313],
       [ 1.18575755e-322,  8.63423259e-312],
       [             nan,  8.63423259e-312],
       [ 1.90979621e-313,  2.33419537e-313],
       [ 1.90979621e-313,  8.63434410e-312],
       [ 8.63416899e-312,  8.61530291e-312],
       [ 1.90979621e-313,  3.60739284e-313],
       [ 4.94065646e-324,  8.63434410e-312],
       [ 1.48219694e-323,  8.63434410e-312],
       [ 8.63434410e-312,  8.63434410e-312],
       [ 9.88131292e-323,  6.95251968e-310],
       [ 0.00000000e+000,  8.63434410e-312],
       [ 4.03179200e-313,  4.45619116e-313],
       [ 9.88131292e-323,  6.95251968e-310],
       [ 0.00000000e+000,  4.45619116e-313],
       [ 4.88059032e-313,  5.30498948e-313],
       [ 9

In [32]:
li_shape = np.ones(10)
li_shape

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
li_shape.reshape((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

*To see the data type.*

In [36]:
li_shape.dtype

dtype('float64')

In [47]:
ttype = np.array((123,5))
first1 = "'ttype' is the variable and '"
sec = "' its data type."
t = ttype.dtype
print( first1 + str(t) + sec)

'ttype' is the variable and 'int32' its data type.


*To find the dimensions of array.*

In [48]:
ttype.ndim

1

In [49]:
sh_var.ndim

3

*To generat random number in numpy.*

In [61]:
np.random.random_integers((10))

8

#*Make 2 arrays and perform arithmetic operations.*

In [76]:
zero0 = np.zeros((4,4))

In [77]:
ones1 = np.ones((4, 4))

In [78]:
ones1 + zero0

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
ones1 - zero0

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
zero0 - ones1

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

In [81]:
zero0 * ones1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
zero0 / ones1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
ones1 / zero0

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [84]:
x = zero0 + 5

In [85]:
y = ones1 * 10

In [86]:
print(y + x)

[[15. 15. 15. 15.]
 [15. 15. 15. 15.]
 [15. 15. 15. 15.]
 [15. 15. 15. 15.]]


In [87]:
y > 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
y < 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [90]:
y[y > 0]

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10.])

*Size of array.*

In [91]:
y.size

16

In [94]:
y.itemsize

8

In [95]:
y.data